name: Backend Lint

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows you to reuse workflows by referencing their YAML files
  workflow_call:
    inputs:
      skip_cache:
        required: false
        type: string

jobs:
  lint:
    name: Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout checkstyle config repository
        uses: actions/checkout@v4
        with:
          repository: dbeaver/dbeaver
          path: dbeaver-config

      - name: Copy checkstyle config
        run: cp dbeaver-config/dbeaver-checkstyle-config.xml ./dbeaver-checkstyle-config.xml

      - name: Remove checkstyle config directory
        run: rm -rf dbeaver-config

      - uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: diff_context
          checkstyle_config: ./dbeaver-checkstyle-config.xml
          fail_on_error: true
