name: Run Jest Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "devel" branch
  pull_request:
    branches: [ "devel" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run-jest-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-node@v3
       with:
        node-version: '16'
     - name: Install dependecies
       run: npm install --legacy-peer-deps
     - name: Install lerna
       run: npm install lerna -g
     - run: lerna bootstrap
     - name: Run tests
     - run: lerna run test --no-bail --stream -- --reporters default github-actions
     
